# Generated by Django 2.1.2 on 2018-11-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dgree',
            new_name='degree',
        ),
    ]
