# Generated by Django 2.1.2 on 2019-01-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190109_1959'),
        ('users', '0003_auto_20190107_1058'),
    ]

    operations = [
    ]
